global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:3000']
  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']